# Generated by Django 2.0.5 on 2018-09-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'proposal', 'verbose_name_plural': 'proposals'},
        ),
        migrations.AlterModelTable(
            name='proposal',
            table='proposals',
        ),
    ]
