# Generated by Django 2.0.5 on 2018-09-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved at'),
        ),
    ]
