# Generated by Django 2.0.5 on 2018-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_core_organizer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a Core Organizer', verbose_name='Core Organizer Status'),
        ),
    ]
