# Generated by Django 2.0.5 on 2018-09-05 20:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='O', max_length=6, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_core_organizer',
            field=models.BooleanField(default=False, help_text='Is the user a core organizer', verbose_name='core organizer status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='Is the user a volunteer', verbose_name='volunteer status'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_id',
            field=models.CharField(default='Not assigned', max_length=32, verbose_name='Ticket Id'),
        ),
        migrations.AddField(
            model_name='user',
            name='tshirt_size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra_large'), ('XXL', 'double extra large')], default='L', max_length=10, verbose_name='Tshirt Size'),
        ),
    ]
