# Generated by Django 2.0.5 on 2018-09-24 14:44

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171024_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not_selected', 'Not Selected'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='not_selected', max_length=12, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_core_organizer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a Core Organizer', verbose_name='User is core_organizer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a Volunteer', verbose_name='User is volunteer'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=13, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Ticket Id'),
        ),
        migrations.AddField(
            model_name='user',
            name='tshirt_size',
            field=models.CharField(choices=[('not_selected', 'Not Selected'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large'), ('extra_extra_large', 'Extra Extra Large')], default='not_selected', max_length=30, verbose_name='Tshirt Size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Of Joining'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff Status'),
        ),
    ]
