# Generated by Django 2.2.3 on 2019-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180924_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_core_organizer',
            field=models.BooleanField(blank=True, default=False, help_text='Designates whether this user is a Core Organizer', verbose_name='User is core_organizer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(blank=True, default=False, help_text='Designates whether this user is a Volunteer', verbose_name='User is volunteer'),
        ),
    ]
