# Generated by Django 2.0.8 on 2018-12-14 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import uuid_upload_path.storage
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='image')),
                ('image_poi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name="image's Point of Interest")),
                ('posted_at', models.CharField(choices=[('fb', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin')], max_length=10, verbose_name='Posted at platform')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled at')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('posted_time', models.DateTimeField(blank=True, null=True, verbose_name='Posted at')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Content Text')),
                ('is_approved', models.BooleanField(default=False, help_text='is the post approved by Nexus administrator?', verbose_name='Is post approved')),
                ('is_posted', models.BooleanField(default=False, help_text='is the post published?', verbose_name='Is posted')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
