# Generated by Django 2.0.5 on 2018-08-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-scheduled_time']},
        ),
    ]
